# Generated by Django 2.1.7 on 2019-03-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(db_index=True, unique=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('site', models.IntegerField()),
            ],
        ),
    ]
