# Generated by Django 2.1.7 on 2019-03-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20190304_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestructure',
            name='page',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='pagestructure',
            unique_together={('page', 'site')},
        ),
    ]
